kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sso-client
  namespace: test
  labels:
    k8s-app: sso-client
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: sso-client
  template:
    metadata:
      labels:
        k8s-app: sso-client
        name: sso-client
    spec:
      hostNetwork: false
      nodeSelector:
        nodeRole: data
      volumes:
        - name: config
          configMap:
            name: sso-client-configmap          
        
      containers:
        - image: docker.registry.cscloud.com/sso-client:1.0
          name: sso-client
          volumeMounts:
            - mountPath: "/config/keycloak.json"
              name: "config"
              subPath: "keycloak.json"
          env:
            - name: TEST.ENV0
              value: TEST.JAVA_INPUT
            - name: TEST.ENV1
              value: TEST.ENV_INPUT  
  
          ports:
            - containerPort: 3000 

---
apiVersion: v1
kind: Service
metadata:
  name: sso-client
  namespace: test
spec:
  selector:
    k8s-app: sso-client
  ports:
  - port: 3000
    targetPort: 3000
    
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sso-client
  namespace: test
spec:
  rules:
  - host: sso.client.cscloud.com
    http:
      paths:
        - path: 
          backend:
            serviceName: sso-client
            servicePort: 3000            