#!/bin/sh

git pull

mvn clean

mvn package

docker build -t docker.registry.cscloud.com/sso-client:1.0 .

docker push docker.registry.cscloud.com/sso-client:1.0

docker rmi docker.registry.cscloud.com/sso-client:1.0 

kubectl delete configmap sso-client-configmap -n test
  
kubectl create configmap sso-client-configmap --namespace=test --from-file=./auth.config.properties

kubectl delete -f ./01-sso-client.dpm.yml

kubectl apply -f ./01-sso-client.dpm.yml