#!/bin/sh

git pull

cp ./config.test.properties ./src/main/resources/config/config.properties

mvn clean

mvn package

docker build -t docker.registry.cscloud.com/sso-client:1.0 .

docker push docker.registry.cscloud.com/sso-client:1.0

docker rmi docker.registry.cscloud.com/sso-client:1.0 

kubectl delete -f ./01-sso-client.dpm.yml

kubectl apply -f ./01-sso-client.dpm.yml